### ISSUE TITLE
Falla con número válido

### ISSUE THREAD

**Issue by felipesilvadv** [open-source-uc/validate-uc-number-py#1]
Lo probé con mi número de alumno y retornó False. No sé como se verifica que el número es o no válido, pero falló con el mio.

**Comment by lopezjurip** [comment]
Cual es tu número (si es que se puede saber)? para que se pueda probar

quizás cambió el algoritmo en estos 5-6 años

**Comment by felipesilvadv** [comment]
mi número es 15635570, si me fijé que el proyecto era de como el 2015, pero mi número de alumno también es del 2015, así que por eso abrí la issue

**Comment by wachunei** [comment]
Confirmo, arroja false 😮 https://runkit.com/embed/zpv6b6o3kn72

**Comment by agucova** [comment]
Resuelto por #2
